check: "2m"

summary:
  enable: true
  interval: "10m"
  
ui:
  show_streamers: true

twitch:
  enable: true
  proxy:
    http: ""
    socks: ""
  channels:
    - "forsen"

kick:
  enable: true
  proxy:
    http: ""
    socks: ""
  channels:
    - "forsen"

youtube:
  enable: true
  proxy:
    http: "127.0.0.1:10808"
    socks: ""
  channels:
    - "forsen"

wtv:
  enable: true
  proxy:
    http: ""
    socks: ""
  channels:
    - "forsen"